clear
read -p "Enter domain: " domain 
ip=$(ip -4 addr show eth0 | grep -oP "(?<=inet ).*(?=/)")
echo ""
printf 'create dns site '$domain' @ '$ip' (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    echo "--- create " $domain " dns site"

    echo "; BIND @ generated by iyc
;
"'$TTL'"    86400
@       IN      SOA     $domain. root.$domain. (
                              1         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                          86400 )       ; Negative Cache TTL
;
@       IN      NS      $domain.
@       IN      A       $ip
www     IN      A       $ip
*.$domain.     IN      A       $ip" >> db.$domain

    sudo mv db.$domain /etc/bind/
    echo "--- dns " $domain " move done!"

    echo "//=== "$domain" ==="  >> /etc/bind/named.conf.local
    echo "zone "$domain" IN {
        type master;
        file \"/etc/bind/db.$domain\";
    };"  >> /etc/bind/named.conf.local
    echo "--- dns " $domain " named.conf.local done!"

    systemctl restart named
    echo "--- dns " $domain " named restarted!"

    echo "--- dns " $domain " DONE!!"

else
    echo "--- dns " $domain " canceled!!"
fi

